repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: detect-private-key

-   repo: https://github.com/PyCQA/doc8
    rev: 0.10.1
    hooks:
    -   id: doc8
        name: doc8
        description: This hook runs doc8 for linting docs
        entry: python -m doc8
        args: ["--config=setup.cfg"]
        language: python
        files: \.rst$

-   repo: https://github.com/thibaudcolas/pre-commit-stylelint.git
    rev: v14.6.1
    hooks:
    -   id: stylelint
        files: \.scss$
        additional_dependencies:
        -   stylelint@14.6.1
        -   stylelint-config-prettier-scss@0.0.1
        -   stylelint-config-standard-scss@3.0.0

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
    -   id: prettier
        types_or: [sass, scss, css, javascript, html]
